language: java

sudo: false

before_install:
  - export PROFILE=ri

script:
  - unset PROFILE
  - jdk_switcher use oraclejdk8
  - mvn clean verify -P ri
  - jdk_switcher use oraclejdk7
  - mvn clean verify -P bp

after_success:
  - mvn clean test jacoco:report coveralls:report

notifications:
  email:
    on_failure: change
